data_dir: !!python/object/apply:pathlib._local.PosixPath
- /home/elias/PycharmProjects/aideml/input
desc_file: null
goal: Predict the sales price for each house
eval: Use the RMSE metric between the logarithm of the predicted and observed values.
log_dir: !!python/object/apply:pathlib._local.PosixPath
- /home/elias/PycharmProjects/aideml/logs/2-translucent-spaniel-of-promotion
workspace_dir: !!python/object/apply:pathlib._local.PosixPath
- /home/elias/PycharmProjects/aideml/workspaces/2-translucent-spaniel-of-promotion
preprocess_data: true
copy_data: true
exp_name: 2-translucent-spaniel-of-promotion
exec:
  timeout: 3600
  agent_file_name: runfile.py
  format_tb_ipython: false
generate_report: true
report:
  model: gpt-4.1
  temp: 1.0
agent:
  steps: 20
  k_fold_validation: 5
  expose_prediction: false
  data_preview: true
  code:
    model: o4-mini
    temp: 0.5
  feedback:
    model: gpt-4.1-mini
    temp: 0.5
  search:
    max_debug_depth: 3
    debug_prob: 0.5
    num_drafts: 5
